### ISSUE TITLE
HardwareState enum missing for nifgen

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#558] opened 2017-11-03 12:07 UTC
```
    def get_hardware_state(self):
        '''get_hardware_state

        Returns the current hardware state of the device and, if the device is
        in the hardware error state, the current hardware error.

        Note: Hardware states do not necessarily correspond to NI-FGEN states.

        Returns:
            state (enums.HardwareState): Returns the hardware state of the signal generator.

                **Defined Values**
```
As per above code **get_hardware_state** has to return enums.HardwareState enum. There is no such enum in enums.py

**Comment by marcoskirsch** [comment] 2017-11-03 12:45
Duplicate of #538

**Closed by marcoskirsch** 2017-11-03 12:45 UTC
Labels: nifgen

**Comment by injaleea** [comment] 2017-11-03 18:50
Need to enable test_get_hardware_state from system_tests once this got fixed
