### ISSUE TITLE
The examples path in documentation is ambiguous

### ISSUE THREAD

**Issue by sbethur** [ni/nimi-python#1682] opened 2022-01-13 16:43 UTC
### Description of issue

In the [Usage](https://nimi-python.readthedocs.io/en/master/nidcpower.html#usage) section, the text says:

> Additional examples for NI-DCPower are located in src/nidcpower/examples/ directory.

The path is ambiguous - it can mean the src folder in the GitHub repo or src folder on a Linux machine with nimi-python module installed. It should unambiguously mean the src folder in the GitHub repo.

**Comment by marcoskirsch** [comment] 2022-03-28 20:29
Duplicate of #1612.

**Closed by marcoskirsch** 2022-03-28 20:29 UTC
Labels: duplicate, docs
