### ISSUE TITLE
nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure.

### ISSUE THREAD

**Issue by chesterknurek** [ni/nimi-python#2061] opened 2024-05-09 12:18 UTC
import nidcpower
# Configure the session.

with nidcpower.Session(resource_name='PXI1Slot3/0') as session:

This snippet of code produces this error: nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure.

I have qty 2 PXIe-4163 sitting inside a PXIe-1084 mainframe with PXIe-8301 Thunderbolt interface card.

I reset the configuration data in MAX and tried renaming the cards but no luck.

**Comment by marcoskirsch** [comment] 2024-05-10 03:10
Hello

You have a legitimate problem in your system, but it is not a bug in the `nidcpower` Python module. The Python module is loading the driver runtime and calling into it correctly and the driver runtime is returning this error.

The more appropriate forum for this sort of issue is [NI Discussion Forums](https://forums.ni.com/t5/Discussion-Forums/ct-p/discussion-forums) or to contact NI support directly.

We have seen lots of problems with buggy Thunderbolt implementation in several vendor PCs. When you reach out to support be sure to include enough information where they can help you:

* PC this running on
* Operating System
* NI-DCPower driver runtime version
* Screenshot of what you see in MAX when you select the board (the screen where calibration data is shows)
* Can you reset in MAX?
* Can you self test in MAX?
* Have you used this NI hardware in any other configurations successfully?

FYI @tobiasgordon 

Closing the issue.

**Closed** 2024-05-10 03:11 UTC
Labels: bug, invalid

**Comment by chesterknurek** [comment] 2024-05-10 11:50
Thankyou for the immediate reply.

I will answer the items below (for your records).

For the record, I have qty 2 systems, one having Thunderbolt and the other having MXI interfaces.
Both (MXI and thunderbolt) have issue so it is not entirely Thunderbolt problem.

-Chet

From: Marcos ***@***.***>
Date: Thursday, May 9, 2024 at 11:11 PM
To: ni/nimi-python ***@***.***>
Cc: Chet Knurek (cknurek) ***@***.***>, Author ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)

Hello

You have a legitimate problem in your system, but it is not a bug in the nidcpower Python module. The Python module is loading the driver runtime and calling into it correctly and the driver runtime is returning this error.

The more appropriate forum for this sort of issue is NI Discussion Forums<https://forums.ni.com/t5/Discussion-Forums/ct-p/discussion-forums> or to contact NI support directly.

We have seen lots of problems with buggy Thunderbolt implementation in several vendor PCs. When you reach out to support be sure to include enough information where they can help you:

  *   PC this running on
Del Precision 3430 (i7)

  *   Operating System
Windows 10 Corporate

  *   NI-DCPower driver runtime version
  *   Screenshot of what you see in MAX when you select the board (the screen where calibration data is shows)
  *   Can you reset in MAX?
YES

  *   Can you self test in MAX?
YES

  *   Have you used this NI hardware in any other configurations successfully?
YES, using C# language, qty 3 PXIe-4163s work flawlessly, together, in a homebrew silicon photonics test station here at Cisco.

FYI @tobiasgordon<https://github.com/tobiasgordon>

Closing the issue.

**Comment by marcoskirsch** [comment] 2024-05-10 17:05
> YES, using C# language, qty 3 PXIe-4163s work flawlessly, together, in a homebrew silicon photonics test station here at Cisco.

Can you run a C# program  that uses NI-DCPower .NET API on the same system in which you see the Python failures? That would be very strange!

**Comment by chesterknurek** [comment] 2024-05-10 17:14
The C# app is compiled with:

NationalInstruments.Common
NationalInstruments.ModularInstruments.Common
NationalInstruments.ModularInstruments.ModualInstrumentsSystem
NationalInstruments.ModularInstruments.NIDCPower.Fx45

I did notice the error that the Python driver reported indicated an IVI: Unrecoverable Failure.

I don’t know IVI, but there is a separate tab in MAX for a configuration one can setup using NIDCPOWER.
Is IVI required?

I have qty 3 SMUS here in NJ. And qty SMUS in CA.

They are $33K each, so maybe I am the first trying the python driver….

Thankyou for your replies.

Whatever I can do on this end to assist, let me know.

-Chet

From: Marcos ***@***.***>
Date: Friday, May 10, 2024 at 1:05 PM
To: ni/nimi-python ***@***.***>
Cc: Chet Knurek (cknurek) ***@***.***>, Author ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)

YES, using C# language, qty 3 PXIe-4163s work flawlessly, together, in a homebrew silicon photonics test station here at Cisco.

Can you run a C# program that uses NI-DCPower .NET API on the same system in which you see the Python failures? That would be very strange!

**Comment by chesterknurek** [comment] 2024-05-10 17:18
I am using the .NET Framework 4.6.1

From: Chet Knurek (cknurek) ***@***.***>
Date: Friday, May 10, 2024 at 1:14 PM
To: ni/nimi-python ***@***.***>, ni/nimi-python ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)
The C# app is compiled with:

NationalInstruments.Common
NationalInstruments.ModularInstruments.Common
NationalInstruments.ModularInstruments.ModualInstrumentsSystem
NationalInstruments.ModularInstruments.NIDCPower.Fx45

I did notice the error that the Python driver reported indicated an IVI: Unrecoverable Failure.

I don’t know IVI, but there is a separate tab in MAX for a configuration one can setup using NIDCPOWER.
Is IVI required?

I have qty 3 SMUS here in NJ. And qty SMUS in CA.

They are $33K each, so maybe I am the first trying the python driver….

Thankyou for your replies.

Whatever I can do on this end to assist, let me know.

-Chet

From: Marcos ***@***.***>
Date: Friday, May 10, 2024 at 1:05 PM
To: ni/nimi-python ***@***.***>
Cc: Chet Knurek (cknurek) ***@***.***>, Author ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)

YES, using C# language, qty 3 PXIe-4163s work flawlessly, together, in a homebrew silicon photonics test station here at Cisco.

Can you run a C# program that uses NI-DCPower .NET API on the same system in which you see the Python failures? That would be very strange!

**Comment by chesterknurek** [comment] 2024-05-10 17:21
NIDCPower 21.5.0

C:\Program Files (x86)\IVI Foundation\IVI\Microsoft.Net\Framework32\v4.5.50709\NationalInstruments.ModularInstruments.NIDCPower 21.5.0\NationalInstruments.ModularInstruments.NIDCPower.Fx45.dll

From: Chet Knurek (cknurek) ***@***.***>
Date: Friday, May 10, 2024 at 1:17 PM
To: ni/nimi-python ***@***.***>, ni/nimi-python ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)
I am using the .NET Framework 4.6.1

From: Chet Knurek (cknurek) ***@***.***>
Date: Friday, May 10, 2024 at 1:14 PM
To: ni/nimi-python ***@***.***>, ni/nimi-python ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)
The C# app is compiled with:

NationalInstruments.Common
NationalInstruments.ModularInstruments.Common
NationalInstruments.ModularInstruments.ModualInstrumentsSystem
NationalInstruments.ModularInstruments.NIDCPower.Fx45

I did notice the error that the Python driver reported indicated an IVI: Unrecoverable Failure.

I don’t know IVI, but there is a separate tab in MAX for a configuration one can setup using NIDCPOWER.
Is IVI required?

I have qty 3 SMUS here in NJ. And qty SMUS in CA.

They are $33K each, so maybe I am the first trying the python driver….

Thankyou for your replies.

Whatever I can do on this end to assist, let me know.

-Chet

From: Marcos ***@***.***>
Date: Friday, May 10, 2024 at 1:05 PM
To: ni/nimi-python ***@***.***>
Cc: Chet Knurek (cknurek) ***@***.***>, Author ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)

YES, using C# language, qty 3 PXIe-4163s work flawlessly, together, in a homebrew silicon photonics test station here at Cisco.

Can you run a C# program that uses NI-DCPower .NET API on the same system in which you see the Python failures? That would be very strange!

**Comment by marcoskirsch** [comment] 2024-05-10 17:23
> I did notice the error that the Python driver reported indicated an IVI: Unrecoverable Failure.
> I don’t know IVI, but there is a separate tab in MAX for a configuration one can setup using NIDCPOWER.
Is IVI required?

NI-DCPower uses IVI under the hood for some things, and the error code is either coming from IVI or is coming from the driver but using an error code defined by IVI.

> I have qty 3 SMUS here in NJ. And qty SMUS in CA.
> They are $33K each, so maybe I am the first trying the python driver….

You are most definitely not the first one using PXIe-4163 with out Python module.

> Whatever I can do on this end to assist, let me know.

What I asked before: Can you run a C# program that uses NI-DCPower .NET API **on the same system** in which you see the Python failures?

**Comment by chesterknurek** [comment] 2024-05-10 17:25
Yes.
I first tried the python driver with the  Thunderbolt config (NJ) and then with  the MXI config (CA).
Same error on both systems.

From: Marcos ***@***.***>
Date: Friday, May 10, 2024 at 1:23 PM
To: ni/nimi-python ***@***.***>
Cc: Chet Knurek (cknurek) ***@***.***>, Author ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)

I did notice the error that the Python driver reported indicated an IVI: Unrecoverable Failure.
I don’t know IVI, but there is a separate tab in MAX for a configuration one can setup using NIDCPOWER.
Is IVI required?

NI-DCPower uses IVI under the hood for some things, and the error code is either coming from IVI or is coming from the driver but using an error code defined by IVI.

I have qty 3 SMUS here in NJ. And qty SMUS in CA.
They are $33K each, so maybe I am the first trying the python driver….

You are most definitely not the first one using PXIe-4163 with out Python module.

Whatever I can do on this end to assist, let me know.

What I asked before: Can you run a C# program that uses NI-DCPower .NET API on the same system in which you see the Python failures?

**Comment by marcoskirsch** [comment] 2024-05-10 17:28
> Yes.

Ok, so a problem with the `nidcpower` Python module is completely ruled out. I think you should go through NI support, Please provide as much detail as you can including troubleshooting steps. Good luck!

**Comment by chesterknurek** [comment] 2024-05-10 17:28
I coded a small command line app with arguments to config a channel on the SMU in C#.
Works.

-Chet

From: C Knurek ***@***.***>
Date: Friday, May 10, 2024 at 1:26 PM
To: ni/nimi-python ***@***.***>
Cc: Chet Knurek (cknurek) ***@***.***>, Your activity ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)
Yes.
I first tried the python driver with the Thunderbolt config (NJ) and then with the MXI config (CA).
Same error on both systems.

From: Marcos ***@***.***>
Date: Friday, May 10, 2024 at 1:23 PM
To: ni/nimi-python ***@***.***>
Cc: Chet Knurek (cknurek) ***@***.***>, Author ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)

I did notice the error that the Python driver reported indicated an IVI: Unrecoverable Failure.
I don’t know IVI, but there is a separate tab in MAX for a configuration one can setup using NIDCPOWER.
Is IVI required?

NI-DCPower uses IVI under the hood for some things, and the error code is either coming from IVI or is coming from the driver but using an error code defined by IVI.

I have qty 3 SMUS here in NJ. And qty SMUS in CA.
They are $33K each, so maybe I am the first trying the python driver….

You are most definitely not the first one using PXIe-4163 with out Python module.

Whatever I can do on this end to assist, let me know.

What I asked before: Can you run a C# program that uses NI-DCPower .NET API on the same system in which you see the Python failures?

**Comment by chesterknurek** [comment] 2024-05-10 17:33
Thankyou Marcos,

-Chet

From: Marcos ***@***.***>
Date: Friday, May 10, 2024 at 1:29 PM
To: ni/nimi-python ***@***.***>
Cc: Chet Knurek (cknurek) ***@***.***>, Author ***@***.***>
Subject: Re: [ni/nimi-python] nidcpower.errors.DriverError: -1074135040: IVI: Unrecoverable Failure. (Issue #2061)

Yes.

Ok, so a problem with the nidcpower Python module is completely ruled out. I think you should go through NI support, Please provide as much detail as you can including troubleshooting steps. Good luck!
