### ISSUE TITLE
Warning about function while making drivers

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#525] opened 2017-10-24 12:57 UTC
Making drivers, reports some warning about function not found in metadata and one of the fake unit test fails.

For NI-DCPower
```
     Generating: C:/Users/Administrator/Desktop/fgentests/wo1/nimi-python/bin/nidcpower/nidcpower/session.py
Warning: "ClearError" not found in function metadata. Typo? Generated code will be funky!
Warning: "MeasureMultiple" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureOutputFunction" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureCurrentLimit" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureOutputFunction" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureVoltageLimit" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureOutputEnabled" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureOutputEnabled" not found in function metadata. Typo? Generated code will be funky!
     Generating: C:/Users/Administrator/Desktop/fgentests/wo1/nimi-python/docs/nidcpower/functions.rst
Warning: "MeasureMultiple" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureOutputFunction" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureCurrentLimit" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureOutputFunction" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureVoltageLimit" not found in function metadata. Typo? Generated code will be funky!
```
NI-DMM
```
     Generating: C:/Users/Administrator/Desktop/fgentests/wo1/nimi-python/bin/nidmm/nidmm/session.py
Warning: "ConfigureThermistorType" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureThermistorType" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureThermistorType" not found in function metadata. Typo? Generated code will be funky!
     Generating: C:/Users/Administrator/Desktop/fgentests/wo1/nimi-python/docs/nidmm/functions.rst
Warning: "ConfigureThermistorType" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureThermistorType" not found in function metadata. Typo? Generated code will be funky!
Warning: "ConfigureThermistorType" not found in function metadata. Typo? Generated code will be funky!
```
NI-Switch
```
     Generating: C:/Users/Administrator/Desktop/fgentests/wo1/nimi-python/bin/niswitch/niswitch/session.py
Warning: "ClearError" not found in function metadata. Typo? Generated code will be funky!
Warning: "IsScanning" not found in function metadata. Typo? Generated code will be funky!
Warning: "InitWithOptions" not found in function metadata. Typo? Generated code will be funky!
Warning: "init" not found in function metadata. Typo? Generated code will be funky!
Warning: "init" not found in function metadata. Typo? Generated code will be funky!
Warning: "InitWithOptions" not found in function metadata. Typo? Generated code will be funky!
     Generating: C:/Users/Administrator/Desktop/fgentests/wo1/nimi-python/docs/niswitch/functions.rst
Warning: "IsScanning" not found in function metadata. Typo? Generated code will be funky!
Warning: "InitWithOptions" not found in function metadata. Typo? Generated code will be funky!
Warning: "init" not found in function metadata. Typo? Generated code will be funky!
```
Test failed for NI-Fake
```
bin/nifake/nifake/tests/test_session.py::TestSession::test_return_multiple_types FAILED
self = <test_session.TestSession object at 0x000000000523DEF0>

    def test_return_multiple_types(self):
        self.patched_library.niFake_ReturnMultipleTypes.side_effect = self.side_effects_helper.niFake_ReturnMultipleTypes
        boolean_val = True
        int32_val = 32
        int64_val = 6000000000
        enum_val = nifake.Turtle.LEONARDO
        float_val = 1.23
        float_enum_val = nifake.FloatEnum._6_5
        array_val = [0, 1, 2]
        array_size = len(array_val)
        string_val = 'Testing is fun?'
        self.side_effects_helper['ReturnMultipleTypes']['return'] = len(string_val)
        self.side_effects_helper['ReturnMultipleTypes']['aBoolean'] = boolean_val
        self.side_effects_helper['ReturnMultipleTypes']['anInt32'] = int32_val
        self.side_effects_helper['ReturnMultipleTypes']['anInt64'] = int64_val
        self.side_effects_helper['ReturnMultipleTypes']['anIntEnum'] = enum_val.value
        self.side_effects_helper['ReturnMultipleTypes']['aFloat'] = float_val
        self.side_effects_helper['ReturnMultipleTypes']['aFloatEnum'] = float_enum_val.value
        self.side_effects_helper['ReturnMultipleTypes']['anArray'] = array_val
        self.side_effects_helper['ReturnMultipleTypes']['aString'] = string_val
        self.side_effects_helper['ReturnMultipleTypes']['return'] = 0
        with nifake.Session('dev1') as session:
            result_boolean, result_int32, result_int64, result_enum, result_float, result_float_enum, result_array, result_string = session.return_multiple_types(array_size)
            assert result_boolean == boolean_val
            assert isinstance(result_boolean, bool)
            assert result_int32 == int32_val
            assert isinstance(result_int32, int)
            assert result_int64 == int64_val
>           assert isinstance(result_int64, int)
E           assert False
E            +  where False = isinstance(6000000000L, int)

bin\nifake\nifake\tests\test_session.py:323: AssertionError
```

**Comment by Fladolcetta** [comment] 2017-10-24 14:16
Closing as duplicate of #489

**Closed by Fladolcetta** 2017-10-24 14:16 UTC
