### ISSUE TITLE
calling nidcpower measure_multiple causes python to crash

### ISSUE THREAD

**Issue by injaleea** [ni/nimi-python#445] opened 2017-10-10 09:49 UTC
Calling nidcpower measure_multiple causes python environment to crash when doing pytest.

```
import nidcpower
import pytest
import re


@pytest.fixture(scope='function')
def session():
    with nidcpower.Session('FakeDevice', '', False, 'Simulate=1, DriverSetup=Model:4143; BoardType:PXIe') as simulated_session:
        yield simulated_session


def test_measure_multiple(session):
    session.source_mode = nidcpower.SourceMode.SINGLE_POINT
    '''session.configure_aperture_time(0, nidcpower.ApertureTimeUnits.SECONDS)'''
    #session.voltage_level = 1
    count = 10
    #session.measure_when = nidcpower.MeasureWhen.ON_DEMAND
    with session.initiate():
        voltage_measurements, current_measurements = session.measure_multiple()
    assert len(voltage_measurements) == 4   # measuremultiple will return a reading for all channel , since 4143 has 4 channel expecting 4 readings 
    assert len(current_measurements) == 4 
    assert isinstance(voltage_measurement[1], float)  
    assert isinstance(current_measurements[1], float) 

```
Also noticed that assertion on test_get_attribute_string fails sometime when it is expecting 4143  session.instrument_model is returning as 4110.[Failure was consistent and disappeared after reboot]

**Comment by marcoskirsch** [comment] 2017-10-10 14:39
Duplicate of #444.

**Closed by marcoskirsch** 2017-10-10 14:39 UTC
Labels: bug
