### ISSUE TITLE
Public methods of Session (and others) have no documentation

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#323] opened 2017-09-15 16:44 UTC
Public methods such as initiate(), which is hand-coded, has no docstring. Also, it doesn't show up in ReadTheDocs. We need to make sure all our public API is properly documented.

**Comment by Fladolcetta** [comment] 2017-11-06 23:23
Closed as a duplicate of #457

**Closed by Fladolcetta** 2017-11-06 23:23 UTC
Labels: docs
