### ISSUE TITLE
nifgen.Session.SendSoftwareTrigger documentation is really wrong

### ISSUE THREAD

**Issue by marcoskirsch** [ni/nimi-python#546] opened 2017-10-30 22:49 UTC
See:
http://nimi-python.readthedocs.io/en/master/nifgen/functions.html#nifgen.send_software_edge_trigger

This comes from internal NI sources, and is incorrect in CVI FP as well. We still need to file an NI internal bug.

**Comment by Fladolcetta** [comment] 2017-11-27 20:27
Duplicate of #597

**Closed by Fladolcetta** 2017-11-27 20:27 UTC
Labels: docs, nifgen
