### ISSUE TITLE
dcpower Mis-match between code and docs

### ISSUE THREAD

**Issue by charterchap** [ni/nimi-python#527] opened 2017-10-25 19:51 UTC
enums.py defines:
nidcpower.MeasurementTypes.MEASURE_CURRENT
Docs say:
nidcpower.MeasurementTypes.NIDCPOWER_VAL_MEASURE_CURRENT

I'm looking at 0e3bad7c

**Comment by Fladolcetta** [comment] 2017-10-25 21:06
Closed as duplicate of #502

**Closed by Fladolcetta** 2017-10-25 21:06 UTC
